version: '3.8'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/app/
    ports:
      - '8000:8000'
    env_file:
      - ./backend/.env
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: postgres_db
    env_file:
      - ./backend/.env.db
